import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

buildscript {
  dependencies {
    classpath libs.kotlinPlugin
    classpath libs.spotlessPlugin
    classpath libs.dokkaPlugin
    classpath libs.animalSnifferPlugin
    classpath libs.publishPlugin
  }

  repositories {
    mavenCentral()
    gradlePluginPortal()
  }
}

allprojects {
  repositories {
    mavenCentral()
  }
}

subprojects {
  apply plugin: 'com.diffplug.spotless'
  spotless {
    kotlin {
      target('**/*.kt')
      ktfmt(libs.ktfmt.get().version).googleStyle()
    }
  }

  tasks.withType(KotlinCompile).configureEach {
    compilerOptions {
      jvmTarget = JvmTarget.JVM_1_8
      freeCompilerArgs.addAll([
          '-progressive',
          '-Xjvm-default=all',
      ])
    }
  }

  tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = JavaVersion.VERSION_1_8.toString()
    targetCompatibility = JavaVersion.VERSION_1_8.toString()
  }

  plugins.withId('com.vanniktech.maven.publish') {
    project.apply plugin: 'ru.vyarus.animalsniffer'

    dependencies {
      signature 'org.codehaus.mojo.signature:java18:1.0@signature'
      signature 'net.sf.androidscents.signature:android-api-level-21:5.0.1_r2@signature'
    }
  }
}
