[libraries]
kotlinPlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.0"
spotlessPlugin = 'com.diffplug.spotless:spotless-plugin-gradle:8.1.0'
dokkaPlugin = "org.jetbrains.dokka:dokka-gradle-plugin:2.1.0"
animalSnifferPlugin = "ru.vyarus:gradle-animalsniffer-plugin:2.0.1"
publishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.35.0"
ktfmt = "com.facebook:ktfmt:0.61"
crossword = "com.jakewharton.crossword:crossword:0.4.0"
